timeout: 30m
steps:
- id: kubeadm
  name: 'gcr.io/jumperfly/packer-virtualbox-builder'
  env:
    - PACKER_BUILD_ARGS=-except kubeadm-master.vagrant.kubeadm-master
- id: kubeadm-master
  name: 'gcr.io/jumperfly/packer-virtualbox-builder'
  env:
    - PACKER_BUILD_ARGS=-except kubeadm.vagrant.kubeadm
